# --- Состояния для ConversationHandler ---
(ADMIN_ADD_LOGIN, ADMIN_ADD_PASSWORD, ADMIN_ADD_MMR,ADMIN_ADD_CALIBRATION,
 ADMIN_EDIT_CHOOSE_ID, ADMIN_EDIT_CHOOSE_FIELD, ADMIN_EDIT_NEW_VALUE,
 USER_RENT_SELECT_ACCOUNT, USER_RENT_SELECT_DURATION,
 ADMIN_DELETE_CHOOSE_ID,ADMIN_ADD_BEHAVIOR) = range(11)
(
    RETURN_CONFIRM_UPDATE,
    RETURN_SELECT_FIELDS,
    RETURN_INPUT_MMR,
    RETURN_INPUT_BEHAVIOR
) = range(200, 204)
(WAIT_FOR_EMAIL_CODE,WAIT_FOR_2FA_CONFIRM) = range(1000, 1002)
(ADMIN_ADD_2FA_ASK, ADMIN_ADD_EMAIL, ADMIN_ADD_EMAIL_PASSWORD,ADMIN_EDIT_EMAIL_CHOOSE_FIELD ) = range(300, 304)